plugins { id 'com.android.application' }
android {
    namespace 'ca.campusday.app'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'ca.campusday.app'
        minSdk 28
        targetSdk 35
        versionCode 4
        versionName '1.2'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
